# -*- coding: utf-8 -*-
"""k mean

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AtB909lG-RMjs3bSKKdY5PwoVTdk5P3c
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cv2

from PIL import Image
img=Image.open("cat.jpg")

from sklearn.cluster import KMeans



img

type(img)

img_ar=np.asarray(img)

img_ar.shape

plt.imshow(img_ar)

img_red=img_ar.copy()

plt.imshow(img_red[:,:,0])

plt.imshow(img_red[:,:,0],cmap='gray')

img_red[:,:,1]=0

plt.imshow(img_red)

img_red[:,:,0]=0
plt.imshow(img_red)

img_red[:,:,2]=0
plt.imshow(img_red)

new_img=cv2.resize(img_ar,(1000,2000))
plt.imshow(new_img)

plt.imshow(new_img)

w_ratio=.5
h_ratio=.5

new_img=cv2.resize(img_ar,(0,0),img_ar,w_ratio,h_ratio)

plt.imshow(new_img)

new_img.shape

new_img=cv2.flip(img_ar,0)
plt.imshow(new_img)

new_img=cv2.flip(img_ar,1)
plt.imshow(new_img)

new_img=cv2.flip(img_ar,-1)
plt.imshow(new_img)

blur_filter=np.ones((3,3))/9.0
blur_filter

output_blur=cv2.blur(img_ar,(50,50))
plt.imshow(output_blur)

output_blur=cv2.blur(img_ar,(100,100))
plt.imshow(output_blur)

output_blur=cv2.blur(img_ar,(50,5))
plt.imshow(output_blur)

